### ISSUE TITLE
Wiki Page instead of README ?

### ISSUE THREAD

**Issue by gunawanwijaya** [arangodb/arangojs#500] opened 2018-01-31 18:12 UTC
can we have a wiki page for API & all related stuff? instead of a very long readme

**Comment by Simran-B** [comment] 2018-01-31 20:44
We want to split the long readme into smaller files and put them in a subfolder "docs" if I'm not mistaken. A wiki is not really an option, because we might want to pull the docs and build them into the hosted online documentation at some point.

**Comment by gunawanwijaya** [comment] 2018-02-08 14:15
okay then, can't wait for a better and well documented docs, fell free to close this issue

**Comment by pluma** [comment] 2018-02-20 10:54
I'm closing this as a duplicate of #123.

**Comment by pluma** [comment] 2018-03-06 18:43
Forgot to actually close this.

**Closed by pluma** 2018-03-06 18:43 UTC
Labels: documentation, enhancement
