### ISSUE TITLE
Support for complex bind parameters in template strings

### ISSUE THREAD

**Issue by natejgardner** [arangodb/arangojs#575] opened 2018-10-05 23:46 UTC
```ts
let myParam: MyType[] = [ {property: "value", otherStuff: { moreStuff: ["value1", "value2"], evenMoreStuff: 1} }, {property: "value3", otherStuff: { moreStuff: ["value4", "value5"], evenMoreStuff: 7} }]

const query = aql`
    let myData = ${myParam}
    for element in myData
        return element
`
// Errors out.

let response = await this.db.query(query).all();
return Promise.resolve(result);
```

Results in the following error:
```
[ts]
Argument of type 'MyType[]' is not assignable to parameter of type 'AqlValue'.
  Type 'MyType[]' is not assignable to type 'AqlLiteral'.
    Property 'toAQL' is missing in type 'MyType[]'.
(parameter) input: MyType[]
```

It seems that simple types are allowed as bind parameters, but I can't easily pass in a serializable object or json. If I pass in json, it takes it as a string.

However, when I use bind parameters explicitly:

```ts
let myParam: MyType[] = [ {property: "value", otherStuff: { moreStuff: ["value1", "value2"], evenMoreStuff: 1} }, {property: "value3", otherStuff: { moreStuff: ["value4", "value5"], evenMoreStuff: 7} }]

const query = { query: `
    let myData = @myParam
    for element in myData
        return element
    `, bindVars: {"myParam": myParam}}

let response = await this.db.query(query).all();
return Promise.resolve(result);
```

everything works as expected. 

I would prefer to be able to use template string syntax for everything rather than only for simple types.

**Comment by pluma** [comment] 2018-10-09 14:06
You're right, the type is currently too strict. It should probably accept whatever `JSON.stringify` accepts, which I'm guessing is `any`. I'm currently on vacation so I can't push a fix but in the meantime you can work around this by passing the template argument `as any` to avoid the type check.

**Comment by pluma** [comment] 2018-10-18 08:50
I'll be back in office on Monday and sort this out. Simplifying the type of AqlValue to include any should be sufficient but I'm not sure how that interacts with the type suggestions so I'll have to thoroughly test this first.

**Comment by pluma** [comment] 2018-10-22 16:04
@natejgardner I can't reproduce this problem. Can you give me an example type definition that causes this?

**Comment by pluma** [comment] 2018-10-22 16:15
@natejgardner I've added a test case for this issue which doesn't seem to cause any problems. Normally the aql template should accept anything that derives from object so I'm not sure what data type you're using.

**Comment by pluma** [comment] 2018-11-05 09:59
@natejgardner I can't reproduce this problem, so I'm closing the issue for now. I have no idea what might cause your type not to match the [rather broad list in the code](https://github.com/arangodb/arangojs/blob/v6.7.0/src/aql-query.ts#L16) considering even an `Array` usually at least matches `object`.

If you can provide an example type that breaks or can point out what's wrong with the test case I've added, feel free to reopen this issue. If you want to troubleshoot this together, hit me up on the Community Slack.

**Comment by natejgardner** [comment] 2018-11-06 02:56
@pluma Apologies for not responding. I just saw these! Any types a developer has defined will cause this issue.

For example:

```ts
class MyClass {
    someData: string;
}
```

```ts
let foo: MyClass[] = [{someData: "hello"}]

const aqlQuery = aql`
let myData = ${foo}
    for element in myData
        return element
`

let response = await this.db.query(query).all();
return Promise.resolve(result); 
```

will reproduce the issue.

**Comment by pluma** [comment] 2018-11-07 10:14
@natejgardner can you clarify which version of TypeScript and which version of arangojs you're using? I've added a variant of the test case that uses a class instead of an interface and it doesn't show the problem.

However your example causes an error for me in the type definition of `MyClass` (because `someData` lacks an initialiser). I'm not sure if this indicates a difference in the tsconfig or the TypeScript version.

An array should match the type `object`, which is permitted by `aql` regardless of the type of its contents. I've added `any[]` to the type signature of `aql` so maybe that will help in your case. This adjustment will be available in the next release of arangojs, scheduled for later today.

**Comment by pluma** [comment] 2018-11-07 10:15
@natejgardner also knowing your tsconfig might probably help.

**Comment by pluma** [comment] 2018-11-07 11:52
@natejgardner please give v6.8.0 a try and see if that solves your problem.

**Comment by pluma** [comment] 2018-12-03 12:04
@natejgardner I've been unable to reproduce this problem and have no further information that would help reproducing the errors you've seen. Please keep in mind that arangojs tracks the latest version of TypeScript so this may be a problem caused by using an older version of `tsc` (e.g. 2.x). I'm closing this issue for now. Please feel free to reopen this issue if you can provide the information I've requested.

**Closed by pluma** 2018-12-03 12:04 UTC
Labels: bug, typescript
