### ISSUE TITLE
Error: connect EADDRNOTAVAIL - maxsockets being ignored?

### ISSUE THREAD

**Issue by samuelgoldenbaum** [arangodb/arangojs#44] opened 2015-06-20 10:58 UTC
Testing performance of saving docs and having the following error thrown every few thousand writes:
```
{ [Error: connect EADDRNOTAVAIL]
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'connect',
  request: 
   { domain: null,
     _events: { response: [Object], error: [Function] },
     _maxListeners: 10,
     output: [],
     outputEncodings: [],
     writable: true,
     _last: false,
     chunkedEncoding: false,
     shouldKeepAlive: true,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _headerSent: true,
     _header: 'POST /_db/loadtest/_api/document/?collection=load HTTP/1.1\r\ncontent-type: application/json\r\ncontent-length: 169\r\nx-arango-version: 20300\r\nHost: localhost:8000\r\nConnection: keep-alive\r\n\r\n',
     _hasBody: true,
     _trailer: '',
     finished: true,
     _hangupClose: false,
     socket: 
      { _connecting: false,
        _handle: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        onend: [Function: socketOnEnd],
        destroyed: true,
        bytesRead: 0,
        _bytesDispatched: 0,
        _pendingData: 'POST /_db/loadtest/_api/document/?collection=load HTTP/1.1\r\ncontent-type: application/json\r\ncontent-length: 169\r\nx-arango-version: 20300\r\nHost: localhost:8000\r\nConnection: keep-alive\r\n\r\n{"id":16313,"type":9,"connections":[100,59,26,58],"positions":[{"time":"2015-06-20T10:49:32.749Z","type":9,"position":{"lat":-122.423246,"lng":37.779388,"radius":250}}]}',
        _pendingEncoding: 'utf8',
        parser: [Object],
        _httpMessage: [Circular],
        ondata: [Function: socketOnData],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     connection: 
      { _connecting: false,
        _handle: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        onend: [Function: socketOnEnd],
        destroyed: true,
        bytesRead: 0,
        _bytesDispatched: 0,
        _pendingData: 'POST /_db/loadtest/_api/document/?collection=load HTTP/1.1\r\ncontent-type: application/json\r\ncontent-length: 169\r\nx-arango-version: 20300\r\nHost: localhost:8000\r\nConnection: keep-alive\r\n\r\n{"id":16313,"type":9,"connections":[100,59,26,58],"positions":[{"time":"2015-06-20T10:49:32.749Z","type":9,"position":{"lat":-122.423246,"lng":37.779388,"radius":250}}]}',
        _pendingEncoding: 'utf8',
        parser: [Object],
        _httpMessage: [Circular],
        ondata: [Function: socketOnData],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     agent: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        options: [Object],
        requests: {},
        sockets: [Object],
        maxSockets: 5,
        createConnection: [Function] },
     socketPath: undefined,
     method: 'POST',
     path: '/_db/loadtest/_api/document/?collection=load',
     _headers: 
      { 'content-type': 'application/json',
        'content-length': 169,
        'x-arango-version': 20300,
        host: 'localhost:8000' },
     _headerNames: 
      { 'content-type': 'content-type',
        'content-length': 'content-length',
        'x-arango-version': 'x-arango-version',
        host: 'Host' },
     parser: 
      { _headers: [],
        _url: '',
        onHeaders: [Function: parserOnHeaders],
        onHeadersComplete: [Function: parserOnHeadersComplete],
        onBody: [Function: parserOnBody],
        onMessageComplete: [Function: parserOnMessageComplete],
        socket: [Object],
        incoming: null,
        maxHeaderPairs: 2000,
        onIncoming: [Function: parserOnIncomingClient] } } }
```
I believe it has something to do with no more available sockets on my machine - but thought that  {maxSockets: 5} would control that? I have changed maxSockets from 1 to 25 and keep having the same result. I see keepalive is enabled by default so assume new connections are not being fired up?
Below is the script I am using to test with:
```
var moment = require('moment'),
	opts = {maxSockets: 5},
	Agent = require('http').Agent;

var db = require('arangojs')({
	url: 'http://localhost:8000',
	databaseName: 'loadtest',
	agent: new Agent(opts)
});

var recs = 1000000,
	currentDoc = 0,
	type,
	start = new Date(),
	collection;

function save() {
	type = Math.round(Math.random() * 10) + 1;
	collection
		.save({
			'id': currentDoc,
			'type': type,
			'connections': [
				Math.round(Math.random() * 100) + 1,
				Math.round(Math.random() * 100) + 1,
				Math.round(Math.random() * 100) + 1,
				Math.round(Math.random() * 100) + 1
			],
			'positions': [
				{
					'time': new Date(),
					'type': type,
					'position': {'lat': -122.423246, 'lng': 37.779388, 'radius': 250}
				}
			]
		},
		function (err, result) {
			if (err || result.error) {
				return console.error(err);
			}
			console.log('inserted ' + currentDoc + ' of ' + recs);
			if (currentDoc === recs) {
				return console.log('inserted ' + currentDoc + ' in ' + moment.utc(moment(new Date(), "DD/MM/YYYY HH:mm:ss").diff(moment(start, "DD/MM/YYYY HH:mm:ss"))).format("HH:mm:ss"));
			}
			currentDoc++;
			save();
		});
}

db.collection('load', function (err, result) {
	if (err) {
		console.error(err);
		return;
	}
	collection = result;
	save();
});
```

*UPDATE:*
Only seems to happen when durability is set to soft and the waitForSync is set to false on the collection - I assume then this is an arangodb issue and not a driver issue? or possibly both?

**Comment by pluma** [comment] 2015-06-21 13:04
Instead of passing in the agent itself, just pass in `agentOptions: {maxSockets: 5}`. The HTTP Agent provided by node.js does not use keep-alive by default, which may explain why you're running out of sockets. The `agent` option is only really useful if you want to provide your own agent implementation (which is not normally necessary).

**Comment by samuelgoldenbaum** [comment] 2015-06-21 15:41
Thanks Alan. I did as suggested, below is the script:
```
var moment = require('moment');

var db = require('arangojs')({
	url: 'http://localhost:8000',
	agentOptions: {maxSockets: 5},
	databaseName: 'loadtest'
});

var recs = 1000000,
	startDoc = 10122492 + 1,
	currentDoc = 0,
	type,
	start = new Date(),
	collection;

function save() {
	type = Math.round(Math.random() * 10) + 1;
	collection
		.save({
			'id': startDoc + currentDoc,
			'type': type,
			'connections': [
				Math.round(Math.random() * 100) + 1,
				Math.round(Math.random() * 100) + 1,
				Math.round(Math.random() * 100) + 1,
				Math.round(Math.random() * 100) + 1
			],
			'positions': [
				{
					'time': new Date(),
					'type': type,
					'position': {'lat': -122.423246, 'lng': 37.779388, 'radius': 250}
				}
			]
		},
		function (err, result) {
			if (err || result.error) {
				return console.error(err);
			}
			console.log('inserted ' + currentDoc + ' of ' + recs);
			if (currentDoc === recs) {
				return console.log('inserted ' + currentDoc + ' in ' + moment.utc(moment(new Date(), "DD/MM/YYYY HH:mm:ss").diff(moment(start, "DD/MM/YYYY HH:mm:ss"))).format("HH:mm:ss"));
			}
			currentDoc++;
			save();
		});
}

db.collection('load', function (err, result) {
	if (err) {
		console.error(err);
		return;
	}
	collection = result;
	console.info('starting: ' + start);
	save();
});
```

after a few seconds I get:
```
{ [Error: connect ETIMEDOUT]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  request: 
   { domain: null,
     _events: { response: [Object], error: [Function] },
     _maxListeners: 10,
     output: [],
     outputEncodings: [],
     writable: true,
     _last: false,
     chunkedEncoding: false,
     shouldKeepAlive: true,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _headerSent: true,
     _header: 'POST /_db/loadtest/_api/document/?collection=load HTTP/1.1\r\ncontent-type: application/json\r\ncontent-length: 170\r\nx-arango-version: 20300\r\nHost: localhost:8000\r\nConnection: keep-alive\r\n\r\n',
     _hasBody: true,
     _trailer: '',
     finished: true,
     _hangupClose: false,
     socket: 
      { _connecting: false,
        _handle: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        onend: [Function: socketOnEnd],
        destroyed: true,
        bytesRead: 0,
        _bytesDispatched: 0,
        _pendingData: 'POST /_db/loadtest/_api/document/?collection=load HTTP/1.1\r\ncontent-type: application/json\r\ncontent-length: 170\r\nx-arango-version: 20300\r\nHost: localhost:8000\r\nConnection: keep-alive\r\n\r\n{"id":10136661,"type":6,"connections":[11,38,2,42],"positions":[{"time":"2015-06-21T15:33:36.022Z","type":6,"position":{"lat":-122.423246,"lng":37.779388,"radius":250}}]}',
        _pendingEncoding: 'utf8',
        parser: [Object],
        _httpMessage: [Circular],
        ondata: [Function: socketOnData],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     connection: 
      { _connecting: false,
        _handle: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        onend: [Function: socketOnEnd],
        destroyed: true,
        bytesRead: 0,
        _bytesDispatched: 0,
        _pendingData: 'POST /_db/loadtest/_api/document/?collection=load HTTP/1.1\r\ncontent-type: application/json\r\ncontent-length: 170\r\nx-arango-version: 20300\r\nHost: localhost:8000\r\nConnection: keep-alive\r\n\r\n{"id":10136661,"type":6,"connections":[11,38,2,42],"positions":[{"time":"2015-06-21T15:33:36.022Z","type":6,"position":{"lat":-122.423246,"lng":37.779388,"radius":250}}]}',
        _pendingEncoding: 'utf8',
        parser: [Object],
        _httpMessage: [Circular],
        ondata: [Function: socketOnData],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     agent: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        options: [Object],
        requests: {},
        sockets: [Object],
        maxSockets: 5,
        createConnection: [Function] },
     socketPath: undefined,
     method: 'POST',
     path: '/_db/loadtest/_api/document/?collection=load',
     _headers: 
      { 'content-type': 'application/json',
        'content-length': 170,
        'x-arango-version': 20300,
        host: 'localhost:8000' },
     _headerNames: 
      { 'content-type': 'content-type',
        'content-length': 'content-length',
        'x-arango-version': 'x-arango-version',
        host: 'Host' },
     parser: 
      { _headers: [],
        _url: '',
        onHeaders: [Function: parserOnHeaders],
        onHeadersComplete: [Function: parserOnHeadersComplete],
        onBody: [Function: parserOnBody],
        onMessageComplete: [Function: parserOnMessageComplete],
        socket: [Object],
        incoming: null,
        maxHeaderPairs: 2000,
        onIncoming: [Function: parserOnIncomingClient] } } }

Process finished with exit code 0

```

This is only the case when **wait for sync is set to false**.

**Comment by pluma** [comment] 2015-06-22 08:22
The ETIMEDOUT confirms that the root issue is on the server and that the EADDRNOTAVAIL was just a symptom caused by using node's default behaviour. I'm closing this issue in favour of the arangodb issue. Thanks for bringing this to our attention.

**Closed by pluma** 2015-06-22 08:22 UTC

**Comment by samuelgoldenbaum** [comment] 2015-06-22 11:38
Cool, will keep track of the progress
