### ISSUE TITLE
Sporadic cursor not found error (1600 error code)

### ISSUE THREAD

**Issue by toymachiner62** [arangodb/arangojs#573] opened 2018-09-19 00:50 UTC
I have a troublesome issue where i'm sporadicly getting the dreaded `cursor not found` error. What i've tracked down is that it only seems to happen on queries that return more than 1K records.

Here's the error i'm getting:
```
{ ArangoError: cursor not found
     at new ArangoError (/usr/src/app/node_modules/arangojs/lib/async/error.js:71:21)
     at Object.resolve (/usr/src/app/node_modules/arangojs/lib/async/connection.js:243:32)
     at _hosts.(anonymous function) (/usr/src/app/node_modules/arangojs/lib/async/connection.js:122:26)
     at IncomingMessage.res.on (/usr/src/app/node_modules/arangojs/lib/async/util/request.node.js:48:21)
     at IncomingMessage.emit (events.js:185:15)
     at endReadableNT (_stream_readable.js:1106:12)
     at process._tickCallback (internal/process/next_tick.js:178:19)
   isArangoError: true,
...
```

Here's the relevant code which sporadically causes this error:

```js
console.log('query = ', query)
  db.query(query)
    .then(cursor => {
      // console.log('cursor = ', cursor)
      return cursor.each(result => {
        if (result !== null && result.resourceType !== 'Statement' && result.resourceType !== 'StatementGroup') {
          results.push(result)
          auditRead(req, result)
            .then(() => {
              return Promise.resolve()
            })
            .catch(err => {
              return Promise.reject()
            })
        }
      })
    })
    .then(() => {
      results = Bundle.wrapInBundle(ReqHelpers.getBaseUrl(req), results, BundleType.searchSet)
      results = FhirHelpers.stripArangoAttributesFromBundle(results)
      return res.status(HttpStatus.OK).send(results)
    })
    .catch(err => {
      console.error('err in $everyting catch = ', err)
      if (err.isArangoError) {
        let response = FhirHelpers.generateErrorObject(IssueType.exception, req.path, err.response.body.errorMessage)
        return res.status(err.response.statusCode).send(response)
      } else {
        let response = FhirHelpers.generateErrorObject(IssueType.exception, req.path)
        return res.status(HttpStatus.INTERNAL_SERVER_ERROR).send(response)
      }
    })
}

/**
 * Save audit information for a read
 * @param  {Object} req       The request object
 * @param  {Array}  resources array of resources
 * @return {[type]} [description]
 */
function auditRead (req, resources) {
  return new Promise((resolve, reject) => {
    let event = FhirHelpers.generateAuditEvent(req, FhirHelpers.typeOfAction().read)

    const auditEvents = db.collection('auditevents')
    const auditEdges = db.collection('auditedges')

    auditEvents.save(event)
      .then(info => {
        // If it's an array, save every record as an auditevent, else save the single record as an auditevent
        if (Array.isArray(resources.entry)) {
          for (let resource of resources.entry) {
            let eventEdge = {
              _key: uuidv4(),
              _from: info._id,
              _to: 'clindocs/' + resource.resourceType + '$' + resource.id 
            }
            auditEdges.save(eventEdge)
              .then(edgeInfo => {
                return Promise.resolve()
              })
              .catch(err => {
                return Promise.reject(err)
              })
          }
        }

        return Promise.resolve()
      })
      .catch(err => {
        return Promise.reject(err)
      })
  })
}
```

I'm using arangojs version 6.6.0

**Comment by toymachiner62** [comment] 2018-10-02 17:33
Anything on this?

**Comment by jsteemann** [comment] 2018-10-02 17:48
Sorry, I am not 100% sure about your actual setup still.
The files in https://github.com/arangodb/arangojs/issues/573#issuecomment-424450014 use an ArangoDB version 3.1, which is relatively old.
With that version it is still possible to get intermittent "cursor not found" issue when multiple coordinators are in use and client application requests are sent to any coordinator in a round-robin fashion using a load-balancer.
The reason for this is that cursor state is stored locally on coordinators, and if follow-up requests for a specific cursor are sent to a coordinator that does not know anything about that cursor, it will return HTTP 404.
Later versions of ArangoDB (from 3.3.14 onwards) support forwarding these requests transparently, so it should work in that setup.
It should always work with cursors that return 1000 or less results, because 1000 is the default batch size of cursors, and any results <= 1000 documents will be handled with a single request/response, without any follow-up requests necessary.

So upgrading to 3.3.14 or higher should help.

**Comment by toymachiner62** [comment] 2018-10-02 18:19
Looks like our Dockerfile is using `FROM arangodb:3.3.13 AS base`. 

I'll try updating that and see if it helps

**Comment by jsteemann** [comment] 2018-10-02 18:31
Ok thanks. With 3.3.14 I wouldn't expect this to happen, except if the cursor has timed out meanwhile.
By default, cursors have a timeout of 30 seconds. If something in the client application takes more time than 30 seconds between originally "ordering" a cursor and making a follow-up request to fetch more data from the cursor, then the issue may also occur.
But I was originally assuming this is not the case.

**Comment by toymachiner62** [comment] 2018-10-02 20:54
Your assumption is correct. From start to fail is subsecond.

Tom Caflisch
507.202.0087
TomCaflisch@gmail.com

**Comment by gcallaghan** [comment] 2018-10-08 21:19
Upgraded to 3.3.15 but still have the same issue

```
query =  WITH clindocs
               FOR resource
               IN 0..50 ANY 'REDACTED'
               clinedges
               OPTIONS { "uniqueVertices": "global", "bfs": true }
               FILTER resource._shardkey == 'be43eaee-98d1-4be6-b26c-55d9fe20d24a' RETURN resource
err =  { ArangoError: cursor not found
    at new ArangoError (/usr/src/app/node_modules/arangojs/lib/async/error.js:71:21)
    at Object.resolve (/usr/src/app/node_modules/arangojs/lib/async/connection.js:243:32)
    at _hosts.(anonymous function) (/usr/src/app/node_modules/arangojs/lib/async/connection.js:122:26)
    at IncomingMessage.res.on (/usr/src/app/node_modules/arangojs/lib/async/util/request.node.js:48:21)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
  isArangoError: true,
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [BufferList],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     _events: { end: [Array], data: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'REDACTED',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        _bytesDispatched: 52129536,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        allowHalfOpen: false,
        server: null,
        _server: null,
        parser: null,
        _httpMessage: null,
        [Symbol(asyncId)]: -1,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(bytesRead)]: 0 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: REDACTED',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        _bytesDispatched: 52129536,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        allowHalfOpen: false,
        server: null,
        _server: null,
        parser: null,
        _httpMessage: null,
        [Symbol(asyncId)]: -1,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(bytesRead)]: 0 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { 'x-content-type-options': 'nosniff',
        server: 'ArangoDB',
        connection: 'Keep-Alive',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '75' },
     rawHeaders:
      [ 'X-Content-Type-Options',
        'nosniff',
        'Server',
        'ArangoDB',
        'Connection',
        'Keep-Alive',
        'Content-Type',
        'application/json; charset=utf-8',
        'Content-Length',
        '75' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 404,
     statusMessage: 'Not Found',
     client:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: REDACTED',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        _bytesDispatched: 52129536,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        allowHalfOpen: false,
        server: null,
        _server: null,
        parser: null,
        _httpMessage: null,
        [Symbol(asyncId)]: -1,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(bytesRead)]: 0 },
     _consuming: true,
     _dumped: false,
     req:
      ClientRequest {
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header: 'PUT /_db/REDACTED/_api/cursor/47003911 HTTP/1.1\r\nauthorization: Basic cm9vdDo=\r\ncontent-type: text/plain\r\nx-arango-version: 30308\r\nHost:REDACTED:8529\r\nConnection: keep-alive\r\nContent-Length: 0\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'PUT',
        path: '/_db/REDACTED/_api/cursor/47003911',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     read: [Function],
     body:
      { error: true,
        errorMessage: 'cursor not found',
        code: 404,
        errorNum: 1600 },
     host: 0 },
  statusCode: 404,
  errorNum: 1600,
  code: 404 }
```

Currently running Arango on Kubernetes as a stateful set

```
$ KUBECONFIG=~/.kube/config.dev kubectl get pods
NAME                                               READY     STATUS      RESTARTS   AGE
arangodb-agent-0                                   1/1       Running     0          4h
arangodb-agent-1                                   1/1       Running     0          4h
arangodb-agent-2                                   1/1       Running     0          4h
arangodb-coord-0                                   1/1       Running     0          4h
arangodb-coord-1                                   1/1       Running     0          4h
arangodb-db-0                                      1/1       Running     0          4h
arangodb-db-1                                      1/1       Running     0          4h
arangodb-db-2                                      1/1       Running     0          4h
```

**Comment by jsteemann** [comment] 2018-10-10 07:21
ArangoDB PR 6765 has been merged back into the stable and development branches, and will be released as part of 3.3.18.

**Comment by pluma** [comment] 2018-10-18 08:47
Cursors in arangojs are already "sticky" when arangojs is configured to use multiple servers. If I understand the discussion correctly, there's nothing actionable on the arangojs side and a fix in ArangoDB is in process, so I'm closing this for now. Feel free to reopen if you think the issue has been closed incorrectly.

**Comment by toymachiner62** [comment] 2018-10-25 18:40
@jsteemann I see on dockerhub https://hub.docker.com/r/arangodb/arangodb/tags/ that 3.3.18 was skipped. Is it safe to assume that 3.3.19 contains this fix?

**Comment by jsteemann** [comment] 2018-10-25 21:32
@toymachiner62 : yes, 3.3.18 was skipped for some internal reasons. 3.3.19 contains everything that was supposed to be released with 3.3.18 plus more bugfixes. So yes, 3.3.19 contains the fix.

**Comment by toymachiner62** [comment] 2018-10-25 21:52
Well we upgraded to 3.3.19 and now we no longer get a cursor not found error, but we now get this error

```
(node:1) UnhandledPromiseRejectionWarning: ArangoError: timeout in cluster operation
     at new ArangoError (/usr/src/app/node_modules/arangojs/lib/async/error.js:71:21)
     at Object.resolve (/usr/src/app/node_modules/arangojs/lib/async/connection.js:243:32)
     at _hosts.(anonymous function) (/usr/src/app/node_modules/arangojs/lib/async/connection.js:122:26)
     at IncomingMessage.res.on (/usr/src/app/node_modules/arangojs/lib/async/util/request.node.js:48:21)
     at IncomingMessage.emit (events.js:185:15)
     at endReadableNT (_stream_readable.js:1106:12)
     at process._tickCallback (internal/process/next_tick.js:178:19)
```

**Comment by jsteemann** [comment] 2018-10-25 23:02
Is this reproducible?
And are these errors returned instantly when running a query or is there a delay before these messages come in?
Does this happen for every query, or just some?

**Comment by toymachiner62** [comment] 2018-10-26 01:03
Long deloy. Requests eventually timeout. Happens on every query.

We tinkered with version 3.3.15 - 3.3.19. Seems this new issue was introduced in 3.3.16.

**Comment by jsteemann** [comment] 2018-11-14 09:52
I have no idea why @pluma closed this issue. I have doubt it is resolved already, at least we haven't got feedback it has been resolved.
@toymachiner62 : Did the last suggestion from @lamai93 help in any way?

**Comment by pluma** [comment] 2019-08-06 16:45
@toymachiner62 Can you indicate whether the problem still exists? There has been no activity since last November, so I'm assuming this is either no longer reproducible or has been sufficiently addressed.

**Comment by toymachiner62** [comment] 2019-08-07 17:02
Not sure if it's addressed or not. I no longer work for the same company so I'm not using arango these days.

What we did was go from a clustered Arango to a single instance to get around this issue since it was a serious blocker for us and that solved the issue at hand. I believe the company has actually moved off of Arango due to some of these issues.

**Comment by pluma** [comment] 2019-08-08 14:28
I'm sorry to hear that.

I don't see anything actionable in this issue at this point without a way to reproduce this, so I'm closing this issue now.

If someone comes across a similar problem, please open a new issue on the ArangoDB repo.

**Closed by pluma** 2019-08-08 14:28 UTC
Labels: arangodb

**Comment by westtrade** [comment] 2023-06-06 10:43
arangodb:3.10

Still reproduce this issue

**Comment by deenuy** [comment] 2024-03-02 10:17
2024 and still issue is reproducible on 3.10.9.
