### ISSUE TITLE
Use of VelocityPack

### ISSUE THREAD

**Issue by robross0606** [arangodb/arangojs#744] opened 2021-09-15 17:01 UTC
According to the Arango documentation (and source code) they use [VelocityPack ](https://github.com/arangodb/velocypack)extensively to optimize communications for things like `arangoimport`.  

Any plans for arangojs to leverage VelocityPack?  I'm noticing that things like `collection.import()` are significantly slower on arangojs than they are when using `arangoimport` even though they both leverage the same REST API.

**Comment by robross0606** [comment] 2021-09-15 17:07
There are apparently C++, Java, Go and PHP libraries for VelocityPack.  A Node.js versions appears to have been started, but abandoned?

https://github.com/arangodb/node-velocypack

**Comment by pluma** [comment] 2021-09-30 13:22
There is currently no official support for Velocypack or VST in Node, so we can not support this file format or protocol at this time.

**Comment by pluma** [comment] 2021-09-30 13:22
I'm closing this as a duplicate of #584.

**Closed by pluma** 2021-09-30 13:22 UTC
