### ISSUE TITLE
Create EdgeCollection with database.collection

### ISSUE THREAD

**Issue by XescuGC** [arangodb/arangojs#29] opened 2015-05-03 11:52 UTC
It would be greate if https://github.com/arangodb/arangojs#databasecollection could create a EdgeCollection when the autoCreate is set to true, like https://github.com/arangodb/arangojs#databasecreatecollection does.

**Comment by pluma** [comment] 2015-05-03 13:42
I could see multiple ways to solve this:

1. Add an `edgeCollection` method that works analogous to `collection` the way `createEdgeCollection` works analogous to `createCollection` (i.e. same logic except it also passes `type: 3` when auto-creating the collection).
2. Extend `collection` so it can take a `properties` object of simply a name (like `createCollection` does).

The problem with the first approach is that it duplicates the existing code, which may warrant some refactoring.

The problem with the second approach is that it muddies the semantics: the properties just get discarded if the collection already exists, which may be unexpected; updating the collection with the properties would make sense, but that may be confusing. Also, it requires the user to know that `type: 3` is how you create an edge collection.

In either case there is an additional edge case (no pun intended): what if the user tries to fetch an edge collection but the collection exists and is not an edge collection. Should the fetch fail? It's not strictly an error but it may be confusing to receive a document collection if you weren't expecting one.

**Comment by XescuGC** [comment] 2015-05-03 18:38
I think the best solution is the `1.` and for the edge case the proper solution should be to fail the fetch if you use `db.edgeCollection` and the collection is not a `edgeCollection`.
Should i open a PR?

**Comment by pluma** [comment] 2015-05-03 21:06
Could you have a look at the development version and see whether the function behaves the way you expect it to?

**Comment by XescuGC** [comment] 2015-05-04 07:55
The method 'works' but, if the collection do not exists, it creates the collection and throws this error:
```
Unhandled rejection ArangoError: unknown collection 'collection_name'
  at new ArangoError (/path/to/project/node_modules/arangojs/lib/error.js:10:13)
  at Request._callback (/path/to/project/node_modules/arangojs/lib/connection.js:78:81)
  at Request.self.callback (/path/to/project/node_modules/arangojs/node_modules/request/request.js:368:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/path/to/project/node_modules/arangojs/node_modules/request/request.js:1219:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/path/to/project/node_modules/arangojs/node_modules/request/request.js:1167:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:943:16
  at process._tickCallback (node.js:419:13)
```
And this error also appears now with the `db.collection`.
The way i'm using it is with the `autoCreate`: `db.edgeCollection(collectionName, true)`

And also the documentation example needs an update :smile:  https://github.com/arangodb/arangojs/commit/4e9e782b8a4885a28b6bf1e264c2d57815257f18#diff-04c6e90faac2675aa89e2176d2eec7d8R186

**Comment by pluma** [comment] 2015-05-04 13:18
I've fixed the example. Sorry about that.

I can't replicate your error, though:

If a collection called `potato` already exists, `db.edgeCollection('potato', true)` returns the collection.

If it doesn't exist, `db.edgeCollection('potato', true)` creates and returns the collection.

If it doesn't exist, `db.edgeCollection('potato', false)` fails with a 1203 error.

If it exists and isn't an edge collection, it fails with a 1237 (wrong collection type) error.

What environment are you running the code in? Could you add a rejection handler and see what `reason.name` and `reason.errorNum` are? They should be `"ArangoError"` and `1203` respectively.

**Comment by XescuGC** [comment] 2015-05-04 15:45
I'm actually a little bit confused with this error, i was using promises, now i've changed to callback  and this is the code example:

````
﻿  db.collection(collectionName, true, function(err, collection){
    if (err) return console.log(err);
    console.log('ok')
  })
````
And it don't return with the error, if i remove the `if` and print the error is `null` and yes, it happens with `db.collection` and `db.edgeCollection`. The error don't stop the execution, and the collection is created.

I've put a `console.log(ojb)` https://github.com/arangodb/arangojs/blob/master/lib/error.js#L7 here to see the trace, and the error is the one you mention `1203`, here is a portion of the otupt of the `console.log(obj)`:

```
{ error: true,
  code: 404,
  errorNum: 1203,
  errorMessage: 'unknown collection \'collectionName\'' }
```
I've also added another log https://github.com/arangodb/arangojs/blob/master/lib/connection.js#L78 here to se the response and it comes with the error.

It's like the error is not captured but it's thrown, this only happens when the collection is not created. What i see 

I'm in a OS X Yosemite (10.10.3) and a ArangoDB version: 2.5.2

If you need anything else, just say it :smiley:

**Comment by XescuGC** [comment] 2015-05-04 16:08
I've updated ArangoDB to 2.5.3 and still the same.

**Comment by pluma** [comment] 2015-05-04 18:36
I actually meant whether you're using Node.js, io.js or a browser and whether you're using the native ES6 promises or a 3rd party promises implementation.

**Comment by pluma** [comment] 2015-05-04 18:56
Wait, is the error just showing up in your browser console?

If you're in a browser, auto-creating a collection will log an error to the console because the code first attempts to fetch the collection before attempting to create it. As the first request will return a status code >=400 (i.e. 404) that *request* is logged to the console as an error although the *error* itself is handled in the code.

You can see the same behaviour when visiting the application details page in the admin frontend of ArangoDB if the Foxx app doesn't have a "default" route (i.e. `/` or `/index.html`). The 404 is logged by the browser as an error even though the code is explicitly handling the 404 response.

**Comment by XescuGC** [comment] 2015-05-04 20:43
It's a NodeJS script to migrate from MongoDB to ArangoDB :smile:
NodeJS version: v0.10.33

The error occurs with both of them, callback and Promises, for promises i use bluebird.

Ok i've migrated everything to callbacks, removed all Promises, and the error disappeared. The error comes back when i define the global object Promise:
```
var Promise = require('bluebird');
global.Promise = Promise;
```
If i comment the second line the error disappears. Is this the way to define them no? I've read it here https://github.com/arangodb/arangojs/issues/26

**Comment by XescuGC** [comment] 2015-05-04 21:05
I've tested the `db.edgeCollection(collectionName, true)` and it works, sorry for wasting your time arround it :bow: . I still don't know why if i define the `global.Promise` it throws the errors.

**Comment by pluma** [comment] 2015-05-05 06:37
I'll test it with bluebird. I was using `es6-promise` as it's the closest you can get to the native promises in ES6. Using `global.Promise` is the correct way in non-ES6 environments -- otherwise the driver will not return promises.

**Comment by pluma** [comment] 2015-05-05 06:45
Okay, I've confirmed the issue with bluebird. Interesting. For some reason it complains about an unhandled rejection even though the promise is resolved.

I think what happens is that the promise returned by the API internally is discarded silently because the API internally only uses callbacks. But bluebird tries to be helpful and logs an error message because the promise is rejected without having a rejection handler.

Basically, the promise that is rejected isn't the one that's returned but the one returned by the server request (which is identical to the logic exposed via the `route` API and therefore always creates promises even though the internal logic doesn't use them).

It's a "feature" of bluebird meant to help track unhandled errors. I'll open a new issue and try to figure out how/whether I can work around this behaviour. As the `edgeCollection` function is working fine otherwise, I'm closing this issue.

**Closed by pluma** 2015-05-05 06:45 UTC
Labels: enhancement

**Comment by XescuGC** [comment] 2015-05-05 06:55
Thanks @pluma, i started to think that was my local configuration, because, as you said, it complains about the unhandled error even thought the promise is resolved.
