### ISSUE TITLE
Database `autoCreate` not works with 2.6.0

### ISSUE THREAD

**Issue by kevinprotoss** [arangodb/arangojs#45] opened 2015-06-22 11:36 UTC
Hi,

After update to v2.6.0, I found the database connection with `autoCreate` options enabled does not work any more. I made some further inspect. The log told me

In this line, it gets an error with 404, and errorNum 1228.
https://github.com/arangodb/arangojs/blob/master/lib/database.js#L271
Then the code try to create a new database. However, no error is returned and no database is created.
I guess it might be the reason of default username and password for new arangodb. Nevertheless, some errors should be returned here about that at least.

Thx

Bg,
Kevin

**Comment by pluma** [comment] 2015-06-22 11:48
Are you using authentication in ArangoDB? arangojs currently doesn't handle authentication errors (see #24).

**Comment by kevinprotoss** [comment] 2015-06-22 12:07
Using authentication in ArangoDB doesn't matter to me. I run ArangoDB in docker. I think arangodb docker images start using authentication after 2.6.0.
How can I disable user authentication for arangodb docker? or how can I use user authentication with arangojs?

**Comment by kevinprotoss** [comment] 2015-06-22 12:12
If I use such use such config.url:
```
http://user:pass@localhost:8529
```
It works.

**Comment by pluma** [comment] 2015-06-22 12:38
Okay, then this is a duplicate of #24. I see you already have an open issue with arango-docker about the authentication being enabled by default at https://github.com/arangodb/arangodb-docker/issues/8

**Closed by pluma** 2015-06-22 12:38 UTC

**Comment by kevinprotoss** [comment] 2015-06-22 12:47
Yes, it's a duplicate issue.

I had my answer in the other repo already. Thanks again.
