### ISSUE TITLE
Support ignoreRevs on `Collection.delete()` calls

### ISSUE THREAD

**Issue by robross0606** [arangodb/arangojs#708] opened 2020-12-17 15:15 UTC
The HTTP API for ArangoDB supports revision checking on document removal via the `If-Match` header:

https://www.arangodb.com/docs/stable/http/document-working-with-documents.html#removes-a-document

However, the ArangoJS API doesn't expose this option.  It should be exposed similar to how `Collection.update()` calls used to work prior to 7.x.  Or, at least, how they're _supposed_ to work (#707).

**Comment by pluma** [comment] 2021-01-13 14:35
I'm closing this as a duplicate of #707 as that issue provides more additional information and the solution seems to be to re-implement the `if-match` header from v6.

**Closed by pluma** 2021-01-13 14:35 UTC

**Comment by robross0606** [comment] 2021-01-26 19:27
I'm not sure this should have been closed.  I don't know if `Collection.delete()` on ArangoJS _ever_ supported revision checks via `If-Match`.  #707 is a bug ticket.  I had submitted this as a feature request.  Just want to make sure we're tracking the distinction.
